[package]
name = "stock_scraper"
version = "0.1.0"
authors = ["jan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.18"
file = "1.1.2"
json = "0.12.4"
scraper = "0.12.0"
log = "0.4"